### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by FernandoSanchez-z** [Octitrusendi/mercadoLiebre#1]
punto-1

tiene todos los elementos dados

punto-2

¿El contenido de todos los artículos está centrado?
si, cumple.

 ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles?

cumple

3. ¿El sitio se adapta a distintas resoluciones de pantalla?
si cumple

5. ¿El sitio cuenta con un formulario de registro de usuarios?
cumple

7. ¿El sitio cuenta con un formulario de login?
cumple

9. ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios?
si cumple

10. ¿El search bar es un formulario?
no

12. ¿Se utilizan animaciones y propiedades de transición de CSS?
si

14. Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien.
buen diseño, y buena fluides de las animaciones 
15.Por último, menciona algo que tu compañero podría mejorar.

**Comment by Octitrusendi** [comment]
gracias Fernando!
