### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by gastonrojas** [Octitrusendi/mercadoLiebre#2]
Peer review por Gaston Rojas

Punto1-cumple
Punto 2- no cumple (falto centrar el texto)
Punto 3- cumple
Punto 4- cumple
Punto 5 - cumple
Punto 6- no cumple (falto por el required a los input)
Punto 7- cumple
Punto 8 - cumple
Punto 9 -Esteticamente quedo muy bien! esta bueno el detalle en el loguin de si te olvidaste la contraseña.
Punto 10 - Lo unico q podria revisarse es cuando se hace el hover sobre el producto este se agrande y desplaza a los elementos de abajo. eso porahi se podria arregar dandole una altura fija en el section que contega al articulo. Peor bueno es un detalle nada mas, el resto muy bien!

**Comment by Octitrusendi** [comment]
genial Gastón! gracias por la observación de la altura fija, no se me había ocurrido, lo voy a modificar!
