### ISSUE TITLE
review

### ISSUE THREAD

**Issue by cesarp28** [Octitrusendi/mercadoLiebre#3]
1- cumple con todos los parámetros establecidos por la consigna.
2- algunos de los valores solicitados por la consigna no condicen  en el tamaño de los iconos  y el contenido si cumple con la consigna 
3- cumple con todos los parámetros establecidos por la consigna.
4-cumple con todos los parámetros establecidos por la consigna.
5-cumple con todos los parámetros establecidos por la consigna.
6-cumple con todos los parámetros establecidos por la consigna.
7- cumple con todos los parámetros establecidos por la consigna.
8- faltan algunas animaciones botones y iconos cambiando de color 
9- muy buen manejo de los estilos muy dinámico.
10- realizar las mejoras nombradas anteriormente

**Comment by Octitrusendi** [comment]
gracias por las observaciones!
